### ISSUE TITLE
Андрей Иванов @Innertal, не начисляются бонусы ПОЭ

### ISSUE THREAD

**Issue by NickButcher9** [PortalNetworkDev/telegram_app_network_back#3]

**Comment by NickButcher9** [comment]
![Image](https://github.com/PortalNetworkDev/telegram_app_network_back/assets/78698937/3ab61bc4-a6b4-4c40-88f6-26c7b5e50589)



![Image](https://github.com/PortalNetworkDev/telegram_app_network_back/assets/78698937/474f2e9b-ff36-4f08-9a09-156b5e39db18)

**Comment by darkrain** [comment]
мало тасков выполнил, минимальный вывод от 2-х токенов
