### ISSUE TITLE
Александр @boilzzz, поблема двух аккаунтов

### ISSUE THREAD

**Issue by NickButcher9** [PortalNetworkDev/telegram_app_network_back#6]
Учувствуют 2-а аккаунта

Действия с телефона
1. Зашел с первого аккаунта, подключил кошелек, подтянулся баланс

Действия с ПК
2. Зашёл с второго аккаунта, обновил приложение через троеточие вертикальное.

Подтянулся баланс с друго-го акка, без подключенного кошелька)

![Image](https://github.com/PortalNetworkDev/telegram_app_network_back/assets/78698937/93b50bea-fc74-4512-9b06-1b86433e05de)

**Comment by darkrain** [comment]
Все правильно, когда привязываешь в первый раз, в базу записывается адрес этого кошелька и баланс будет забираться именно с этого кошелька. это делается для того чтобы не было путаницы с кошельками в плане выплат. 

В будущем может сделаем смену кошелька. 

Пока вижу эту проблему не критичной
