### ISSUE TITLE
Александр @boilzzz Сборс задания

### ISSUE THREAD

**Issue by NickButcher9** [PortalNetworkDev/telegram_app_network_back#8]
Сбросилось задание за ликвидность, но пое за него пришли по идеи

![Image](https://github.com/PortalNetworkDev/telegram_app_network_back/assets/78698937/56c31ee2-9315-4cb2-9d75-71eba3fc4a57)

**Comment by darkrain** [comment]
Проверил, все хорошо сейчас.
